@baseUrl = http://localhost:3333
@authToken = {{Authenticate.response.body.data.access_token}}


# @name Register
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "name": "HM Tecnologia Ltda Admin",
    "secret": "Admin@103256",
    "scopes": ["read", "write", "admin"]
}

###


# @name Authenticate
POST {{baseUrl}}/api/v1/auth/token
Content-Type: application/json

{
    "client_id": "944a0a58-ca97-4e47-a275-7f6f11f66f32",
    "client_secret":"Admin@103256"
}

###