@baseUrl = http://localhost:3333


# @name Register
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "name": "HM Tecnologia Ltda Admin",
    "secret": "Admin@103256",
    "scopes": ["read", "write", "admin"]
}

###


# @name Authenticate
POST {{baseUrl}}/api/v1/auth/token
Content-Type: application/json

{
    "client_id": "56ec30b9-1242-4b0e-8f29-6f2ed783b193",
    "client_secret":"Admin@103256"
}

###
