
services:
  email-background-jobs:
    build:
      context: .
      dockerfile: Dockerfile 
      target: production
    container_name: email-background-jobs
    ports:
      - '3333:3333' 
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy 
    networks:
      - server-email-network 
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
      - --dir
      - /bitnami/redis/data
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - server-email-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
      
volumes:
  redis-data:

networks:
  server-email-network:
    driver: bridge 